### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Not support the expr.

### ISSUE THREAD

**Issue by zisudada** [CikeyQi/unidbg-fetch-qsign-shell#12]
the logcat show:

Exception in thread "main" java.lang.IllegalStateException: Not support the expr.
	at moe.fuqiuluo.comm.ArgsParser.<init>(ArgsParser.kt:14)
	at moe.fuqiuluo.comm.ArgsParserKt.invoke(ArgsParser.kt:39)
	at MainKt.main(Main.kt:31)

i just run ./unidbg-fetch-qsign basePath=txlib/8.9.96
I tried to find answers on the internet, but nothing worked

This qsign is downloaded from your repository
so what can i solve this problem？

**Comment by CikeyQi** [comment]
I believe you should use "--basePath=txlib/8.9.96" instead of "basePath=txlib/8.9.96" to specify the version number. Perhaps the mistake lies here. I look forward to your feedback.
